server:
  port: 8082

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.0.113:3306/eshop?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: eshop
    password: eshop
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validation-query: select 'x' from dual


  redis:
    cluster:
      nodes:
        - 192.168.0.110:7001
        - 192.168.0.111:7003
        - 192.168.0.112:7005
        - 192.168.0.112:7006
    timeout: 5000

jedis:
  pool:
    max-active: 1000   # 连接池最大连接数（使用负值表示没有限制)
    max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 10      # 连接池中的最大空闲连接
    min-idle: 5       # 连接池中的最小空闲连接

#mybatis相关配置
mybatis:
  type-aliases-package: com.young.eshop.inventory.model
  mapper-locations: classpath:com/young/eshop/inventory/mapper/mapping/*Mapper.xml


#log记录
logging:
  path: /var/log/young/${spring.application.name}
  level:
    com.young: DEBUG
    org.springframework.boot.actuate.endpoint: WARN
    org.springframework.web.servlet.mvc.method.annotation: WARN


