server:
  port: 8082

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.0.113:3306/eshop?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: eshop
    password: eshop
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query:  select 'x' from dual
  cache:
    ehcache:
      config: ehcache.xml


  redis:
    host: 192.168.0.113
    port: 6379

    timeout: 5000

    lettuce:
      pool:
        max-active: 1000

#log记录
logging:
  path: /var/log/young/${spring.application.name}
  level:
    com.young: DEBUG
    org.springframework.boot.actuate.endpoint: WARN
    org.springframework.web.servlet.mvc.method.annotation: WARN


